<a href="https://colab.research.google.com/github/my-thought-experiments/explore-tensorflow/blob/develop/tf2_basic_syntax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow-gpu==2.0.1

     |████████████████████████████████| 380.8MB 41kB/s 
     |████████████████████████████████| 3.8MB 37.7MB/s 
     |████████████████████████████████| 450kB 51.7MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=427b034c14f89afd12fd877519ab3b16e5fbef4020d094375ab4cbb6a5c9de05
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow 2.2.0rc3 has requirement gast==0.3.3, but you'll have gast 0.2.2 which is incompatible.
ERROR: tensorflow 2.2.0rc3 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 2.0.2 which is incompatible.
ERROR: tensorflow 2.2.0rc3 has requirement tensorflow-estimator<2.3.0,>=2.2.0rc0, but you'll have tensorflow-estimator 2.0.1 which is incompatible.
ERROR: tensorflow-probability 0.10.0rc0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: gast 0.3.3
    Uninstall

In [0]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.0.1'

## Constants

### Defining a constant

In [0]:
tensor = tf.constant([[23, 4], [32, 5]])
tensor

<tf.Tensor: id=2, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32,  5]], dtype=int32)>

In [0]:
tensor.shape

TensorShape([2, 2])

### Getting the values of a constant

In [0]:
tensor.numpy()

array([[23,  4],
       [32,  5]], dtype=int32)

In [0]:
numpy_tensor = np.array(tensor)
numpy_tensor

array([[23,  4],
       [32,  5]], dtype=int32)

In [0]:
# We can convert a numpy array back to tensorflow tensor

tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32,  5]], dtype=int32)>

## Variables

### Defining a variable

In [0]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

### Getting values of a variable

In [0]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### Changing a specific value in the variable

In [0]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operations with tensors

In [0]:
# Addition between a scale and a tensor
tensor + 2

<tf.Tensor: id=24, shape=(2, 2), dtype=int32, numpy=
array([[25,  6],
       [34,  7]], dtype=int32)>

In [0]:
# Multiplication between a scale and a tensor
tensor * 2

<tf.Tensor: id=26, shape=(2, 2), dtype=int32, numpy=
array([[46,  8],
       [64, 10]], dtype=int32)>

In [0]:
# Using numpy on tensor
np.square(tensor)

array([[ 529,   16],
       [1024,   25]], dtype=int32)

In [0]:
np.sqrt(tensor)

array([[4.79583152, 2.        ],
       [5.65685425, 2.23606798]])